import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api.schema"; // generated by openapi-typescript
import { queryClient } from "./queryClient";
import { apiAuthHeader } from "./api-auth";
import { getApiToken, reportUnauthorized } from "@/stores/auth.store";

export const API_URL = "/api";

const api = createFetchClient<paths>({
  baseUrl: API_URL,
});

api.use({
  onRequest({ request }) {
    const header = apiAuthHeader(
      request.url,
      window.location.origin,
      getApiToken(),
    );
    if (header) request.headers.set("Authorization", header.Authorization);
    return request;
  },
  async onResponse({ response: res }) {
    if (res.status === 401) reportUnauthorized();
    if (!res.ok) {
      const json = await res.json().catch(() => {});
      const message = json?.message || res.statusText;
      throw new Error(message);
    }
  },
});

export const $api = createClient(api);

export function invalidateQuery(path: keyof paths, init?: any) {
  queryClient.invalidateQueries({
    queryKey: init ? ["get", path, init] : ["get", path],
  });
}

export type JsonBody<
  P extends keyof paths,
  M extends keyof paths[P],
> = paths[P][M] extends {
  requestBody?: { content: { "application/json": infer B } };
}
  ? B
  : never;

export type JsonRes<
  P extends keyof paths,
  M extends keyof paths[P],
> = paths[P][M] extends {
  responses: { "200": { content: { "application/json": infer B } } };
}
  ? B
  : never;

export default api;
